# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvNXe3DfjWm_sHunvYElpTCjQhr8Bvmi
"""

!pip install streamlit openai langchain langchain_community
import streamlit as st
from langchain.llms import OpenAI

st.title('🦜🔗 Quickstart App')

openai_api_key = st.sidebar.text_input('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')

def generate_response(input_text):
  llm = OpenAI(temperature=0.7, openai_api_key=openai_api_key)
  st.info(llm(input_text))

with st.form('my_form'):
  text = st.text_area('Enter text:', 'What are the three key pieces of advice for learning how to code?')
  submitted = st.form_submit_button('Submit')
  if not openai_api_key.startswith('sk-'):
    st.warning('Please enter your OpenAI API key!', icon='⚠')
  if submitted and openai_api_key.startswith('sk-'):
    generate_response(text)